-- OPTIONAL DEMO ONLY. Never run on production.
begin;
insert into public.brands(id,name,slug,status) values('10000000-0000-4000-8000-000000000100','QHS DEMO','qhs-demo','published') on conflict(id) do nothing;
insert into public.products(id,name,slug,sku,model,category_id,brand_id,short_description,full_description,featured_image,sales_type,price,sale_price,vat,stock_status,stock_quantity,status,featured,is_demo,warranty,application,capacity,division,seo_title,meta_description,canonical_url,og_image,noindex,specs,gallery,documents,videos) values('00000000-0000-4000-8000-000000000001','Cân bàn điện tử 300kg','can-ban-300kg-demo','DEMO-001','QHS-D1','10000000-0000-4000-8000-000000000007','10000000-0000-4000-8000-000000000100','Dữ liệu DEMO để kiểm thử giao diện. Cấu hình và giá chưa phải thông tin thương mại của Quốc Hưng.','Sản phẩm minh họa cho catalogue kỹ thuật. Thông số dưới đây là ví dụ, cần thay bằng dữ liệu đã được xác minh trước khi xuất bản chính thức.','/images/platform.svg','DIRECT',3500000,null,0,'contact',null,'published',true,true,'Cần xác nhận theo cấu hình','Nhà máy, kho vận','300 kg','Cần xác nhận','','','','',true,'[{"label":"Tải trọng minh họa","value":"300 kg"},{"label":"Model minh họa","value":"QHS-D1"}]','[]','[]','[]') on conflict(id) do nothing;
insert into public.products(id,name,slug,sku,model,category_id,brand_id,short_description,full_description,featured_image,sales_type,price,sale_price,vat,stock_status,stock_quantity,status,featured,is_demo,warranty,application,capacity,division,seo_title,meta_description,canonical_url,og_image,noindex,specs,gallery,documents,videos) values('00000000-0000-4000-8000-000000000002','Cân xe tải 80 tấn','can-xe-tai-80-tan-demo','DEMO-002','QHS-D2','10000000-0000-4000-8000-000000000006','10000000-0000-4000-8000-000000000100','Dữ liệu DEMO để kiểm thử giao diện. Cấu hình và giá chưa phải thông tin thương mại của Quốc Hưng.','Sản phẩm minh họa cho catalogue kỹ thuật. Thông số dưới đây là ví dụ, cần thay bằng dữ liệu đã được xác minh trước khi xuất bản chính thức.','/images/truck.svg','PROJECT',null,null,0,'contact',null,'published',true,true,'Cần xác nhận theo cấu hình','Nhà máy, kho vận','80 tấn','Cần xác nhận','','','','',true,'[{"label":"Tải trọng minh họa","value":"80 tấn"},{"label":"Model minh họa","value":"QHS-D2"}]','[]','[]','[]') on conflict(id) do nothing;
insert into public.products(id,name,slug,sku,model,category_id,brand_id,short_description,full_description,featured_image,sales_type,price,sale_price,vat,stock_status,stock_quantity,status,featured,is_demo,warranty,application,capacity,division,seo_title,meta_description,canonical_url,og_image,noindex,specs,gallery,documents,videos) values('00000000-0000-4000-8000-000000000003','Loadcell 2 tấn','loadcell-2-tan-demo','DEMO-003','QHS-D3','10000000-0000-4000-8000-000000000015','10000000-0000-4000-8000-000000000100','Dữ liệu DEMO để kiểm thử giao diện. Cấu hình và giá chưa phải thông tin thương mại của Quốc Hưng.','Sản phẩm minh họa cho catalogue kỹ thuật. Thông số dưới đây là ví dụ, cần thay bằng dữ liệu đã được xác minh trước khi xuất bản chính thức.','/images/loadcell.svg','QUOTE',null,null,0,'contact',null,'published',true,true,'Cần xác nhận theo cấu hình','Nhà máy, kho vận','2 tấn','Cần xác nhận','','','','',true,'[{"label":"Tải trọng minh họa","value":"2 tấn"},{"label":"Model minh họa","value":"QHS-D3"}]','[]','[]','[]') on conflict(id) do nothing;
insert into public.products(id,name,slug,sku,model,category_id,brand_id,short_description,full_description,featured_image,sales_type,price,sale_price,vat,stock_status,stock_quantity,status,featured,is_demo,warranty,application,capacity,division,seo_title,meta_description,canonical_url,og_image,noindex,specs,gallery,documents,videos) values('00000000-0000-4000-8000-000000000004','Bộ chỉ thị cân điện tử','bo-chi-thi-demo','DEMO-004','QHS-D4','10000000-0000-4000-8000-000000000016','10000000-0000-4000-8000-000000000100','Dữ liệu DEMO để kiểm thử giao diện. Cấu hình và giá chưa phải thông tin thương mại của Quốc Hưng.','Sản phẩm minh họa cho catalogue kỹ thuật. Thông số dưới đây là ví dụ, cần thay bằng dữ liệu đã được xác minh trước khi xuất bản chính thức.','/images/indicator.svg','QUOTE',null,null,0,'contact',null,'published',true,true,'Cần xác nhận theo cấu hình','Nhà máy, kho vận','Theo cấu hình','Cần xác nhận','','','','',true,'[{"label":"Tải trọng minh họa","value":"Theo cấu hình"},{"label":"Model minh họa","value":"QHS-D4"}]','[]','[]','[]') on conflict(id) do nothing;
insert into public.posts(id,title,slug,excerpt,content,featured_image,status,seo_title,meta_description,noindex,created_at,is_demo) values('10000000-0000-4000-8000-000000000200','Chọn cân bàn: bắt đầu từ nhu cầu vận hành','chon-can-ban-theo-nhu-cau','Tải trọng, kích thước bàn cân và môi trường làm việc là những yếu tố cần làm rõ.','Nội dung DEMO — bản nháp biên tập.

Xác định khối lượng tối đa của hàng hóa và kích thước kiện hàng. Sau đó trao đổi với đơn vị cung cấp về độ chia, môi trường và yêu cầu kết nối.

Thông số cuối cùng cần được xác nhận trên tài liệu chính thức của thiết bị.','/images/platform.svg','published','','',true,'2026-09-30T00:00:00Z',true) on conflict(id) do nothing;
commit;
