export type Category = {
  id: string;
  name: string;
  slug: string;
  parent_id: string | null;
  description: string;
  seo_content: string;
  status: string;
};
export type Brand = { id: string; name: string; slug: string; status: string };
export type Product = {
  id: string;
  name: string;
  slug: string;
  sku: string;
  model: string;
  category_id: string;
  brand_id: string | null;
  short_description: string;
  full_description: string;
  featured_image: string;
  sales_type: 'DIRECT' | 'QUOTE' | 'PROJECT';
  price: number | null;
  sale_price: number | null;
  vat: number;
  stock_status: string;
  stock_quantity: number | null;
  status: string;
  featured: boolean;
  is_demo: boolean;
  warranty: string;
  application: string;
  capacity: string;
  division: string;
  seo_title: string;
  meta_description: string;
  canonical_url: string;
  og_image: string;
  noindex: boolean;
  specs: { label: string; value: string }[];
  gallery: string[];
  documents: { name: string; url: string }[];
  videos: string[];
};
export type Content = {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  featured_image: string;
  status: string;
  seo_title: string;
  meta_description: string;
  noindex: boolean;
  created_at: string;
  is_demo: boolean;
};
