-- QHS Commerce ONLY. Apply to a new, dedicated Supabase project.
begin;
create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','sales','content','warehouse','customer');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', role public.app_role not null default 'customer', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create function public.has_role(roles public.app_role[]) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.profiles where id=auth.uid() and role=any(roles)); $$;
revoke all on function public.has_role(public.app_role[]) from public;
grant execute on function public.has_role(public.app_role[]) to anon,authenticated;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
create trigger new_auth_user after insert on auth.users for each row execute function public.handle_new_user();
create table public.categories(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'), parent_id uuid references public.categories(id), description text not null default '', seo_content text not null default '', status text not null default 'draft' check(status in ('draft','published','archived')), seo_title text not null default '', meta_description text not null default '', canonical_url text not null default '', og_image text not null default '', noindex boolean not null default false, check(parent_id is distinct from id));
create table public.brands(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text not null unique, status text not null default 'draft' check(status in ('draft','published','archived')), logo text not null default '');
create table public.products(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), name text not null, slug text not null unique, sku text not null unique, model text not null default '', category_id uuid not null references public.categories(id), brand_id uuid references public.brands(id) on delete set null, short_description text not null default '', full_description text not null default '', featured_image text not null default '', sales_type text not null default 'QUOTE' check(sales_type in ('DIRECT','QUOTE','PROJECT')), price numeric(16,2) check(price>=0), sale_price numeric(16,2) check(sale_price is null or (sale_price>=0 and price is not null and sale_price<=price)), vat numeric(5,2) not null default 0 check(vat>=0 and vat<=100), stock_status text not null default 'contact' check(stock_status in ('in_stock','out_of_stock','contact')), stock_quantity integer check(stock_quantity>=0), status text not null default 'draft' check(status in ('draft','published','archived')), featured boolean not null default false, is_demo boolean not null default false, warranty text not null default '', application text not null default '', capacity text not null default '', division text not null default '', specs jsonb not null default '[]' check(jsonb_typeof(specs)='array'), gallery jsonb not null default '[]' check(jsonb_typeof(gallery)='array'), documents jsonb not null default '[]' check(jsonb_typeof(documents)='array'), videos jsonb not null default '[]' check(jsonb_typeof(videos)='array'), seo_title text not null default '', meta_description text not null default '', canonical_url text not null default '', og_image text not null default '', noindex boolean not null default false, search_vector tsvector generated always as (to_tsvector('simple',name||' '||sku||' '||model||' '||short_description||' '||full_description||' '||capacity||' '||application||' '||specs::text)) stored, check(sales_type<>'DIRECT' or price is not null));
create table public.product_variants(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), product_id uuid not null references public.products(id) on delete cascade, sku text not null unique, name text not null, attributes jsonb not null default '{}', price numeric(16,2) check(price>=0), stock_quantity integer not null default 0 check(stock_quantity>=0));
create table public.related_products(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), product_id uuid not null references public.products(id) on delete cascade, related_product_id uuid not null references public.products(id) on delete cascade, relation text not null default 'related' check(relation in ('related','accessory')), unique(product_id,related_product_id), check(product_id<>related_product_id));
create table public.customers(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid unique references auth.users(id), name text not null, email text, phone text, company text, tax_code text, assigned_to uuid references public.profiles(id));
create table public.leads(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, phone text not null, email text, company text, province text, message text not null, product_id uuid references public.products(id) on delete set null, type text not null default 'contact' check(type in ('contact','quote','survey','callback')), source text not null default 'Direct' check(source in ('Organic','Google Ads','Facebook','Direct','Referral','Other')), status text not null default 'NEW', assigned_to uuid references public.profiles(id), customer_id uuid references public.customers(id), utm_source text, utm_medium text, utm_campaign text, utm_content text, utm_term text, landing_page text, referrer text, consent_at timestamptz);
create table public.customer_contacts(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), customer_id uuid not null references public.customers(id) on delete cascade, name text not null, email text, phone text, title text);
create table public.opportunities(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), customer_id uuid references public.customers(id), lead_id uuid references public.leads(id), title text not null, value numeric(16,2) check(value>=0), stage text not null default 'NEW' check(stage in ('NEW','CONTACTED','QUALIFIED','SURVEY','QUOTED','NEGOTIATION','WON','LOST')), probability integer check(probability between 0 and 100), expected_close_date date, assigned_to uuid references public.profiles(id));
create table public.opportunity_activities(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), opportunity_id uuid not null references public.opportunities(id) on delete cascade, created_by uuid references public.profiles(id), type text not null check(type in ('CALL','MEETING','MESSAGE','EMAIL','NOTE','TASK')), description text not null, occurred_at timestamptz not null default now());
create table public.quotations(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), quotation_number text not null unique, customer_id uuid not null references public.customers(id), opportunity_id uuid references public.opportunities(id), status text not null default 'DRAFT' check(status in ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED')), subtotal numeric(16,2) not null default 0 check(subtotal>=0), tax numeric(16,2) not null default 0 check(tax>=0), discount numeric(16,2) not null default 0 check(discount>=0), total numeric(16,2) not null default 0 check(total>=0), notes text, valid_until date);
create table public.quotation_items(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), quotation_id uuid not null references public.quotations(id) on delete cascade, product_id uuid references public.products(id) on delete set null, description text not null, quantity numeric(12,3) not null check(quantity>0), unit_price numeric(16,2) not null check(unit_price>=0), discount numeric(16,2) not null default 0 check(discount>=0), tax numeric(16,2) not null default 0 check(tax>=0), total numeric(16,2) not null check(total>=0));
create table public.tasks(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, customer_id uuid references public.customers(id), opportunity_id uuid references public.opportunities(id), assigned_to uuid references public.profiles(id), due_at timestamptz, status text not null default 'OPEN' check(status in ('OPEN','DONE','CANCELLED')));
create table public.notes(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), customer_id uuid references public.customers(id), opportunity_id uuid references public.opportunities(id), created_by uuid references public.profiles(id), content text not null);
create table public.carts(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid references auth.users(id), anonymous_token_hash text unique, check(user_id is not null or anonymous_token_hash is not null));
create table public.cart_items(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), cart_id uuid not null references public.carts(id) on delete cascade, product_id uuid not null references public.products(id), variant_id uuid references public.product_variants(id), quantity integer not null check(quantity between 1 and 999), unique nulls not distinct(cart_id,product_id,variant_id));
create table public.shipping_addresses(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), user_id uuid not null references auth.users(id), full_name text not null, phone text not null, province text not null, district text, ward text not null, address text not null);
create table public.orders(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), order_number text not null unique, customer_id uuid references public.customers(id), user_id uuid references auth.users(id), status text not null default 'PENDING' check(status in ('PENDING','AWAITING_PAYMENT','PAID','PROCESSING','SHIPPING','COMPLETED','CANCELLED','REFUNDED')), customer_snapshot jsonb not null, shipping_snapshot jsonb not null, subtotal numeric(16,2) not null check(subtotal>=0), tax numeric(16,2) not null default 0 check(tax>=0), shipping_fee numeric(16,2) not null default 0 check(shipping_fee>=0), discount numeric(16,2) not null default 0 check(discount>=0), total numeric(16,2) not null check(total>=0), currency text not null default 'VND', notes text);
create table public.order_items(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, sku text not null, variant_snapshot jsonb, quantity integer not null check(quantity>0), unit_price numeric(16,2) not null check(unit_price>=0), tax numeric(16,2) not null default 0 check(tax>=0), total numeric(16,2) not null check(total>=0));
create table public.payments(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), order_id uuid not null references public.orders(id), provider text not null check(provider in ('COD','BANK_TRANSFER','PAYOS')), provider_reference text unique, idempotency_key text not null unique, amount numeric(16,2) not null check(amount>=0), currency text not null default 'VND', status text not null default 'PENDING' check(status in ('PENDING','PAID','FAILED','REFUNDED')), verified_at timestamptz);
create table public.payment_events(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), provider text not null, event_id text not null, payment_id uuid references public.payments(id), payload jsonb not null, unique(provider,event_id));
create table public.order_status_history(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), order_id uuid not null references public.orders(id), status text not null, created_by uuid references public.profiles(id), note text);
create table public.post_categories(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), name text not null, slug text not null unique, status text not null default 'draft' check(status in ('draft','published','archived')));
create table public.posts(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, slug text not null unique, excerpt text not null default '', content text not null default '', featured_image text not null default '', author_id uuid references public.profiles(id), category_id uuid references public.post_categories(id), published_at timestamptz, status text not null default 'draft' check(status in ('draft','published','archived')), seo_title text not null default '', meta_description text not null default '', canonical_url text not null default '', og_image text not null default '', noindex boolean not null default false, is_demo boolean not null default false);
create table public.pages(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, slug text not null unique, excerpt text not null default '', content text not null default '', featured_image text not null default '', status text not null default 'draft' check(status in ('draft','published','archived')), seo_title text not null default '', meta_description text not null default '', canonical_url text not null default '', og_image text not null default '', noindex boolean not null default false, is_demo boolean not null default false);
create table public.projects(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), title text not null, slug text not null unique, excerpt text not null default '', content text not null default '', featured_image text not null default '', customer_public_name text, publication_consent boolean not null default false, location text, industry text, requirement text, solution text, implementation text, result text, project_date date, gallery jsonb not null default '[]', videos jsonb not null default '[]', status text not null default 'draft' check(status in ('draft','published','archived')), seo_title text not null default '', meta_description text not null default '', canonical_url text not null default '', og_image text not null default '', noindex boolean not null default false, is_demo boolean not null default false, check(status<>'published' or publication_consent=true or is_demo=true));
create table public.project_products(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), project_id uuid not null references public.projects(id) on delete cascade, product_id uuid not null references public.products(id), unique(project_id,product_id));
create table public.faqs(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), question text not null, answer text not null, category_id uuid references public.categories(id), product_id uuid references public.products(id), status text not null default 'draft' check(status in ('draft','published','archived')));
create table public.audit_logs(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), actor_id uuid references auth.users(id), table_name text not null, record_id uuid, action text not null, changed_fields text[]);
create table public.settings(id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), key text not null unique, value jsonb not null default '{}');
create table public.rate_limits(id uuid primary key default gen_random_uuid(), key text not null unique, window_start timestamptz not null, count integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index products_search_idx on public.products using gin(search_vector);
create index products_category_idx on public.products(category_id);
create index products_brand_idx on public.products(brand_id);
create index products_status_idx on public.products(status);
create index categories_parent_idx on public.categories(parent_id);
create index leads_status_idx on public.leads(status);
create index leads_assigned_idx on public.leads(assigned_to);
create index orders_user_idx on public.orders(user_id);
create index opportunities_stage_idx on public.opportunities(stage);
create function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;
alter table public.profiles enable row level security;
create trigger touch_profiles before update on public.profiles for each row execute function public.set_updated_at();
create index profiles_created_idx on public.profiles(created_at);
create policy admin_all on public.profiles for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.categories enable row level security;
create trigger touch_categories before update on public.categories for each row execute function public.set_updated_at();
create index categories_created_idx on public.categories(created_at);
create policy admin_all on public.categories for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.brands enable row level security;
create trigger touch_brands before update on public.brands for each row execute function public.set_updated_at();
create index brands_created_idx on public.brands(created_at);
create policy admin_all on public.brands for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.products enable row level security;
create trigger touch_products before update on public.products for each row execute function public.set_updated_at();
create index products_created_idx on public.products(created_at);
create policy admin_all on public.products for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.product_variants enable row level security;
create trigger touch_product_variants before update on public.product_variants for each row execute function public.set_updated_at();
create index product_variants_created_idx on public.product_variants(created_at);
create policy admin_all on public.product_variants for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.related_products enable row level security;
create trigger touch_related_products before update on public.related_products for each row execute function public.set_updated_at();
create index related_products_created_idx on public.related_products(created_at);
create policy admin_all on public.related_products for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.customers enable row level security;
create trigger touch_customers before update on public.customers for each row execute function public.set_updated_at();
create index customers_created_idx on public.customers(created_at);
create policy admin_all on public.customers for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.leads enable row level security;
create trigger touch_leads before update on public.leads for each row execute function public.set_updated_at();
create index leads_created_idx on public.leads(created_at);
create policy admin_all on public.leads for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.customer_contacts enable row level security;
create trigger touch_customer_contacts before update on public.customer_contacts for each row execute function public.set_updated_at();
create index customer_contacts_created_idx on public.customer_contacts(created_at);
create policy admin_all on public.customer_contacts for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.opportunities enable row level security;
create trigger touch_opportunities before update on public.opportunities for each row execute function public.set_updated_at();
create index opportunities_created_idx on public.opportunities(created_at);
create policy admin_all on public.opportunities for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.opportunity_activities enable row level security;
create trigger touch_opportunity_activities before update on public.opportunity_activities for each row execute function public.set_updated_at();
create index opportunity_activities_created_idx on public.opportunity_activities(created_at);
create policy admin_all on public.opportunity_activities for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.quotations enable row level security;
create trigger touch_quotations before update on public.quotations for each row execute function public.set_updated_at();
create index quotations_created_idx on public.quotations(created_at);
create policy admin_all on public.quotations for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.quotation_items enable row level security;
create trigger touch_quotation_items before update on public.quotation_items for each row execute function public.set_updated_at();
create index quotation_items_created_idx on public.quotation_items(created_at);
create policy admin_all on public.quotation_items for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.tasks enable row level security;
create trigger touch_tasks before update on public.tasks for each row execute function public.set_updated_at();
create index tasks_created_idx on public.tasks(created_at);
create policy admin_all on public.tasks for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.notes enable row level security;
create trigger touch_notes before update on public.notes for each row execute function public.set_updated_at();
create index notes_created_idx on public.notes(created_at);
create policy admin_all on public.notes for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.carts enable row level security;
create trigger touch_carts before update on public.carts for each row execute function public.set_updated_at();
create index carts_created_idx on public.carts(created_at);
create policy admin_all on public.carts for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.cart_items enable row level security;
create trigger touch_cart_items before update on public.cart_items for each row execute function public.set_updated_at();
create index cart_items_created_idx on public.cart_items(created_at);
create policy admin_all on public.cart_items for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.shipping_addresses enable row level security;
create trigger touch_shipping_addresses before update on public.shipping_addresses for each row execute function public.set_updated_at();
create index shipping_addresses_created_idx on public.shipping_addresses(created_at);
create policy admin_all on public.shipping_addresses for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.orders enable row level security;
create trigger touch_orders before update on public.orders for each row execute function public.set_updated_at();
create index orders_created_idx on public.orders(created_at);
create policy admin_all on public.orders for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.order_items enable row level security;
create trigger touch_order_items before update on public.order_items for each row execute function public.set_updated_at();
create index order_items_created_idx on public.order_items(created_at);
create policy admin_all on public.order_items for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.payments enable row level security;
create trigger touch_payments before update on public.payments for each row execute function public.set_updated_at();
create index payments_created_idx on public.payments(created_at);
create policy admin_all on public.payments for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.payment_events enable row level security;
create trigger touch_payment_events before update on public.payment_events for each row execute function public.set_updated_at();
create index payment_events_created_idx on public.payment_events(created_at);
create policy admin_all on public.payment_events for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.order_status_history enable row level security;
create trigger touch_order_status_history before update on public.order_status_history for each row execute function public.set_updated_at();
create index order_status_history_created_idx on public.order_status_history(created_at);
create policy admin_all on public.order_status_history for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.post_categories enable row level security;
create trigger touch_post_categories before update on public.post_categories for each row execute function public.set_updated_at();
create index post_categories_created_idx on public.post_categories(created_at);
create policy admin_all on public.post_categories for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.posts enable row level security;
create trigger touch_posts before update on public.posts for each row execute function public.set_updated_at();
create index posts_created_idx on public.posts(created_at);
create policy admin_all on public.posts for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.pages enable row level security;
create trigger touch_pages before update on public.pages for each row execute function public.set_updated_at();
create index pages_created_idx on public.pages(created_at);
create policy admin_all on public.pages for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.projects enable row level security;
create trigger touch_projects before update on public.projects for each row execute function public.set_updated_at();
create index projects_created_idx on public.projects(created_at);
create policy admin_all on public.projects for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.project_products enable row level security;
create trigger touch_project_products before update on public.project_products for each row execute function public.set_updated_at();
create index project_products_created_idx on public.project_products(created_at);
create policy admin_all on public.project_products for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.faqs enable row level security;
create trigger touch_faqs before update on public.faqs for each row execute function public.set_updated_at();
create index faqs_created_idx on public.faqs(created_at);
create policy admin_all on public.faqs for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.audit_logs enable row level security;
create trigger touch_audit_logs before update on public.audit_logs for each row execute function public.set_updated_at();
create index audit_logs_created_idx on public.audit_logs(created_at);
alter table public.settings enable row level security;
create trigger touch_settings before update on public.settings for each row execute function public.set_updated_at();
create index settings_created_idx on public.settings(created_at);
create policy admin_all on public.settings for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
alter table public.rate_limits enable row level security;
create trigger touch_rate_limits before update on public.rate_limits for each row execute function public.set_updated_at();
create index rate_limits_created_idx on public.rate_limits(created_at);
create policy admin_all on public.rate_limits for all to authenticated using(public.has_role(array['admin']::public.app_role[])) with check(public.has_role(array['admin']::public.app_role[]));
create policy profile_self_read on public.profiles for select to authenticated using(id=auth.uid());
-- No self-update on role-bearing profiles. Role changes require an administrator.
create policy public_published on public.categories for select to anon,authenticated using(status='published');
create policy content_manage on public.categories for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_published on public.brands for select to anon,authenticated using(status='published');
create policy content_manage on public.brands for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_published on public.products for select to anon,authenticated using(status='published');
create policy content_manage on public.products for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_published on public.posts for select to anon,authenticated using(status='published');
create policy content_manage on public.posts for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_published on public.post_categories for select to anon,authenticated using(status='published');
create policy content_manage on public.post_categories for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_published on public.pages for select to anon,authenticated using(status='published');
create policy content_manage on public.pages for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_published on public.projects for select to anon,authenticated using(status='published');
create policy content_manage on public.projects for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_published on public.faqs for select to anon,authenticated using(status='published');
create policy content_manage on public.faqs for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy content_manage on public.product_variants for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_parent on public.product_variants for select to anon,authenticated using(exists(select 1 from public.products p where p.id=product_id and p.status='published'));
create policy content_manage on public.related_products for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_parent on public.related_products for select to anon,authenticated using(exists(select 1 from public.products p where p.id=product_id and p.status='published') and exists(select 1 from public.products p where p.id=related_product_id and p.status='published'));
create policy content_manage on public.project_products for all to authenticated using(public.has_role(array['content']::public.app_role[])) with check(public.has_role(array['content']::public.app_role[]));
create policy public_parent on public.project_products for select to anon,authenticated using(exists(select 1 from public.projects p where p.id=project_id and p.status='published') and exists(select 1 from public.products p where p.id=product_id and p.status='published'));
create policy sales_manage on public.leads for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.customers for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.customer_contacts for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.opportunities for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.opportunity_activities for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.quotations for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.quotation_items for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.tasks for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy sales_manage on public.notes for all to authenticated using(public.has_role(array['sales']::public.app_role[])) with check(public.has_role(array['sales']::public.app_role[]));
create policy staff_read on public.orders for select to authenticated using(public.has_role(array['sales','warehouse']::public.app_role[]));
create policy staff_read on public.order_items for select to authenticated using(public.has_role(array['sales','warehouse']::public.app_role[]));
create policy staff_read on public.order_status_history for select to authenticated using(public.has_role(array['sales','warehouse']::public.app_role[]));
create policy customer_self on public.customers for select to authenticated using(user_id=auth.uid());
create policy addresses_self on public.shipping_addresses for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy own_orders on public.orders for select to authenticated using(user_id=auth.uid());
create policy own_order_items on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create policy own_order_history on public.order_status_history for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create policy own_payments on public.payments for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create policy own_carts on public.carts for select to authenticated using(user_id=auth.uid());
create policy own_cart_items on public.cart_items for select to authenticated using(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid()));
-- Commerce mutations are intentionally server-only until transactional services ship in Phase 2.
create policy audit_read on public.audit_logs for select to authenticated using(public.has_role(array['admin']::public.app_role[]));
create function public.audit_change() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.audit_logs(actor_id,table_name,record_id,action,changed_fields) values(auth.uid(),TG_TABLE_NAME,coalesce(new.id,old.id),TG_OP,array(select jsonb_object_keys(coalesce(to_jsonb(new),to_jsonb(old))))); if TG_OP='DELETE' then return old; end if; return new; end; $$;
create trigger audit_products after insert or update or delete on public.products for each row execute function public.audit_change();
create trigger audit_categories after insert or update or delete on public.categories for each row execute function public.audit_change();
create trigger audit_brands after insert or update or delete on public.brands for each row execute function public.audit_change();
create trigger audit_profiles after insert or update or delete on public.profiles for each row execute function public.audit_change();
create trigger audit_posts after insert or update or delete on public.posts for each row execute function public.audit_change();
create trigger audit_projects after insert or update or delete on public.projects for each row execute function public.audit_change();
create trigger audit_leads after insert or update or delete on public.leads for each row execute function public.audit_change();
create trigger audit_orders after insert or update or delete on public.orders for each row execute function public.audit_change();
create trigger audit_payments after insert or update or delete on public.payments for each row execute function public.audit_change();
create function public.consume_rate_limit(p_key text,p_limit integer,p_window_seconds integer) returns boolean language plpgsql security definer set search_path='' as $$ declare hits integer; begin insert into public.rate_limits(key,window_start,count) values(p_key,now(),1) on conflict(key) do update set count=case when public.rate_limits.window_start<now()-make_interval(secs=>p_window_seconds) then 1 else public.rate_limits.count+1 end,window_start=case when public.rate_limits.window_start<now()-make_interval(secs=>p_window_seconds) then now() else public.rate_limits.window_start end returning count into hits; return hits<=p_limit; end; $$;
revoke all on function public.consume_rate_limit(text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_rate_limit(text,integer,integer) to service_role;
-- Public media must be reviewed before uploading; do not place private documents here.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('products','products',true,5242880,array['image/jpeg','image/png','image/webp']),
('posts','posts',true,5242880,array['image/jpeg','image/png','image/webp']),
('projects','projects',true,5242880,array['image/jpeg','image/png','image/webp']),
('documents','documents',true,10485760,array['application/pdf']),
('avatars','avatars',false,2097152,array['image/jpeg','image/png','image/webp']);
create policy media_upload on storage.objects for insert to authenticated with check(bucket_id in ('products','posts','projects','documents') and public.has_role(array['admin','content']::public.app_role[]));
create policy media_update on storage.objects for update to authenticated using(bucket_id in ('products','posts','projects','documents') and public.has_role(array['admin','content']::public.app_role[])) with check(bucket_id in ('products','posts','projects','documents') and public.has_role(array['admin','content']::public.app_role[]));
create policy media_delete on storage.objects for delete to authenticated using(bucket_id in ('products','posts','projects','documents') and public.has_role(array['admin','content']::public.app_role[]));
create policy media_staff_read on storage.objects for select to authenticated using(bucket_id in ('products','posts','projects','documents') and public.has_role(array['admin','content']::public.app_role[]));
commit;

